plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

pnpFallbackMode: all

pnpMode: loose

nodeLinker: pnpm

yarnPath: .yarn/releases/yarn-3.1.0.cjs
