name: Publish
on:
  push:
    branches:
      - main

jobs:
  build_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: volta-cli/action@v1
      - name: Cache
        id: cache
        uses: actions/cache@v2
        with:
          path: |
            .yarn
            !/.yarn/releases
            !/.yarn/plugins
            !/.yarn/sdks
            !/.yarn/cache
            .parcel-cache
          key: ${{ runner.os }}-yarn2-${{ hashFiles('yarn.lock') }}
      - name: Install
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install
      - name: Build
        run: yarn build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./.dist
          publish_branch: gh-pages
